name: Build

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setting environment variables (1/2)
      run: |
        echo "PROJECT_REPO=$(echo $GITHUB_REPOSITORY | cut -d '/' -f 1)" >> $GITHUB_ENV
        echo "PROJECT_NAME=$(echo $GITHUB_REPOSITORY | cut -d '/' -f 2)" >> $GITHUB_ENV
        echo "PROJECT_VERSION=0.60.1" >> $GITHUB_ENV
        echo "DEPLOY_ARCHIVE='tar.bz2'" >> $GITHUB_ENV
        echo "BINTRAY_USER='mikrosk'" >> $GITHUB_ENV
        # BINTRAY_API_KEY is defined in Travis Settings of freemint/mintlib
        echo "BINTRAY_REPO='lib'" >> $GITHUB_ENV
    - name: Setting environment variables (2/2)
      run: |
        echo "INSTALL_DIR=/tmp/${PROJECT_NAME}" >> $GITHUB_ENV
        echo "DEPLOY_DIR=/tmp/${PROJECT_NAME}-deploy" >> $GITHUB_ENV

    - name: Verify environment variables
      run: echo "$PROJECT_REPO, $PROJECT_NAME, $PROJECT_VERSION, $INSTALL_DIR, $DEPLOY_DIR, $DEPLOY_ARCHIVE, $BINTRAY_USER, $BINTRAY_REPO"

    - uses: actions/checkout@v2

    - name: configure
      run: ./configure

    - name: make
      run: make

    - name: make check
      run: make check

    - name: make distcheck
      run: make distcheck
